version: '3'
services:
  web:
    build:
      context: ./trello
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: npm start
    env_file: .env
    environment:
      PUBLIC_URL: http://0.0.0.0:8080/
      HOST: 0.0.0.0
      PORT: 8080
      NODE_ENV: development
      VUE_APP_API_KEY:
    volumes:
      - ./trello:/usr/src/app
    ports:
      - "8080:8080"
